CREATE TABLE skinApp_skinProfiles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER
        REFERENCES skinApp_users(id) ON DELETE CASCADE NOT NULL, 
    skin_type TEXT, 
    climate TEXT, 
    skin_tone TEXT,  
    age INTEGER
)