CREATE TABLE skinApp_routine (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    user_id INTEGER
        REFERENCES skinApp_users(id) ON DELETE CASCADE NOT NULL, 
    step_number INTEGER, 
    step_name TEXT, 
    product_id INTEGER  
); 